### ISSUE TITLE
How to set the default Partition

### ISSUE THREAD

**Issue by eli-fine-res** [udondan/iam-floyd#425] opened 2023-06-14 15:15 UTC
Hello,

I'm beginning working in GovCloud (Python Pulumi IaC).  I ran into an error using `on_bucket` because it was setting the partition to `aws` and not `aws-us-gov`.  I searched in your codebase and saw that there's a parameter called "default partition", but looking through the documentation I couldn't really understand how to use it https://iam-floyd.readthedocs.io/en/latest/search.html?q=partition&check_keywords=yes&area=default

Ideally it'd be great if I could just set it once and then it would apply for all other things.  Something like this in the entrypoint of the python code:

```

import iam_floyd as statement
statement.DEFAULT_PARTITION = 'aws-us-gov'

```

I'm not sure if something like that is already possible, as I couldn't quite figure out from the compiled JSII Python code exactly what was going on.

(or maybe it'd be `PolicyStatementBase.DEFAULT_PARTITION = 'aws-us-gov' ...?  still trying to look through the giant single JSII compiled python file)

Thank you!

(I was able to figure out that it looks like `partition` is a kwarg basically everywhere, so in the meantime I can use that)

**Comment by udondan** [comment] 2024-02-17 09:31
Closing this as a duplicate of #296. 

But FYI, after the project was stuck for a year now due to jsii issues, jsii and with that Python support is gone. Sorry about that, but I was not able to make the package work again with jsii limitations in place.

**Closed by udondan** 2024-02-17 09:31 UTC
Labels: question
