### ISSUE TITLE
PolicyStatements not compatible with CDK

### ISSUE THREAD

**Issue by kernwig** [udondan/iam-floyd#107] opened 2022-01-26 20:06 UTC
**I'm using the package**

- [ ] iam-floyd
- [x] cdk-iam-floyd

**I'm using the package in language**
- [x] TypeScript/JavaScript (npm)
- [ ] Python (pip)

**Describe the problem**

The statements generated by this library v03.11.0 aren't compatible with CDK v2 PolicyStatement - perhaps because you are generating your own PolicyStatement base classes rather than using the ones from the CDK library? Strict type checking is failing.

I had to write this helper function to convert:

```
import * as iam from "aws-cdk-lib/aws-iam";
import * as iamFloyd from "cdk-iam-floyd";

/**
 * Convert iam-floyd statements to standard CDK PolicyStatements
 */
export function toPermissions(...statements: iamFloyd.PolicyStatement[]): iam.PolicyStatement[] {
  return statements.map((floydStatement) => iam.PolicyStatement.fromJson(floydStatement.toJSON()));
}
```

**Comment by udondan** [comment] 2022-01-27 09:48
Hi Adam,

I cannot reproduce this. We have multiple stacks based on different 2.x CDK versions and no issues. I just tested again with cdk lib 2.8.0 and 2.9.0.

> perhaps because you are generating your own PolicyStatement base classes rather than using the ones from the CDK library?

No, this is not the case. The base class is the PolicyStatement from the cdk-lib. Otherweise this library wouldn't make any sense.

Can you provide more details? Maybe this is related to some specific setting in your tsconfig or how the dependencies/devDependencies/overrides are defiend in your package.json.

Cheers,
Daniel

**Comment by kernwig** [comment] 2022-01-27 16:36
Hmm. When I dug into the multiple layers of PolicyStatement classes, it looked like I was still in iam-floyd, but it's easy to get lost in node_modules. I'm using Serverless Stack on top of CDK, so maybe they can help narrow it down.

**Comment by udondan** [comment] 2022-01-27 17:21
Just to make sure... you're really using the package cdk-iam-floyd and not iam-floyd? The latter indeed does not extend the original PolicyStatement class. That's the main difference between them.

**Comment by kernwig** [comment] 2022-01-27 18:22
Confirmed @udondan .

**Comment by ryansidebottom** [comment] 2022-01-27 23:55
@kernwig how are you using the statements? I ran into some issues at times but it was user error on how we were handling combining arrays.

**Comment by udondan** [comment] 2024-02-17 09:28
Going to close this. We have dozens of stacks in our company using this construct and no issues. If this still persists, please provide a repo I can check out where the problem can be reproduced.

**Closed by udondan** 2024-02-17 09:28 UTC
Labels: bug
